global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9091", "host.docker.internal:9092"]
alerting:
  alertmanagers:
    - static_configs:
        - targets:
        # -alertmanager:9093
  # Load rules once and periodically evaluate them according to the global evaluation intervals
  #rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
